---
title: "R Notebook"
output: html_notebook
---

```{r}
source('~/WaCS/reporting/CIKM2017 - ClusterTree POIs/CIKM2017.R')
## Helper functions converting minutes and hours to seconds
{ minutes <- function(m) m * 60; hours <- function(h) h * 60 * 60 }

## WSU Tests (selected from http://boundingbox.klokantech.com/ )
wsu_bbox <- matrix(c(-84.0693247318,39.7779605403,-84.0612995625,39.7839959297), ncol=2, byrow=T)
# bbox_size(sp::bbox(wsu_bbox)) # := 461.2778 km^2 
wsu_truth <- IntrinsicPOIs(wsu_bbox, sim_length = hours(6), 
                           ped_arr_rate = list(n = 1, p = 5),
                           veh_arr_rate = list(n = 1, p = 10),
                           osm_file = "wsu.osm", batch_mode = minutes(15))
# plotMap(wsu_truth, truth = rsl_cl$cluster)
```

```{r}
## Add uniform noise to SUMO estimates to mimic realistic GPS noise
test_data <- with(wsu_truth$results, {
  sp <- sp + matrix(replicate(2, runif(nrow(sp), min = 0, max = 10)), ncol=2)
  list(sp=sp, cluster=cluster)
})

## View truth data 
exemplars <- wsu_truth$vars[["sumo_net"]]$projectCRS(test_data$sp)@coords
palette(viridis::plasma(15))
plotLeaflet(wsu_truth$vars[["sumo_net"]]$config$bbox) %>%
      addCircles(lng = exemplars[, 1], lat = exemplars[, 2], 
                 col = palette()[match(test_data$cluster, unique(test_data$cluster)) %% length(palette()) + 1L],
                 radius=1.75, stroke = FALSE, fillOpacity = 0.65)


results_wsu <- runValidation(test_data)

## View most stable solution data 
palette(viridis::plasma(15))
rsl_results <- results_wsu$data[["rsl"]][[results_wsu$most_stable]]$cluster
non_noise <- rsl_results != 0
plotLeaflet(wsu_truth$vars[["sumo_net"]]$config$bbox) %>%
      addCircles(lng = exemplars[non_noise, 1], lat = exemplars[non_noise, 2], 
                 col = palette()[match(rsl_results[non_noise], unique(rsl_results[non_noise])) %% length(palette()) + 1L],
                 radius=1.75, stroke = FALSE, fillOpacity = 0.65)



# plot(test_data$sp, col = test_data$cluster)
# plotValidation(results, title = "WSU")
# plot(test_data$sp, col = test_data$cluster + 1)
 # plot(test_data$sp, col = results_wsu$data[["rsl"]][[3]]$cluster + 1)

## Results plotting
title <- "WSU"
suppressMessages({ library("ggplot2", quietly = T) })
ari_plot <- ggplot2::ggplot()
ari_plot + ggplot2::ggtitle(paste0(title, " Validation: ARI")) +
  ggplot2::geom_boxplot(data = results_wsu$results[CVI == "ARI"], aes(x = .id, y = score), # results[.id != "RSL" & CVI == "ARI"]
                        color = sample(viridis::viridis(length(levels(results_wsu$results$.id))))) +
  ggplot2::theme(axis.text.x = element_text(angle = 60, hjust = 1),
                 axis.title.x = element_blank()) +
  ggplot2::labs(y = "Adjusted Rand Index") + ggplot2::ylim(c(0, 1)) + 
  ggplot2::geom_hline(yintercept = results_wsu$results[.id == "RSL" & CVI == "ARI" & index == results_wsu$most_stable]$score, col = "orange")

wsu_all <- list(truth=wsu_truth, validation=results_wsu)
save(wsu_all, file = "~/WaCS/SIGSPATIAL17/wsu.rdata")
```

```{r}
## OSU Tests (selected from http://boundingbox.klokantech.com/ )
osu_bbox <- matrix(c(-83.0179685354,39.9974324509,-83.0098897219,40.0018952624), ncol=2, byrow = T)
# bbox_size(sp::bbox(osu_bbox)) # := 342.27 km^2 
osu_truth <- IntrinsicPOIs(osu_bbox, sim_length = hours(8), 
                           ped_arr_rate = list(n = 5, p = 10), 
                           veh_arr_rate = list(n = 5, p = 10), 
                           osm_file = "osu.osm")

test_set <- osu_truth
test_data <- with(test_set$results, {
  sp <- sp + matrix(replicate(2, runif(nrow(sp), min = 0, max = 10)), ncol=2)
  list(sp=sp, cluster=cluster)
})

## View truth data 
exemplars <- osu_truth$vars[["sumo_net"]]$projectCRS(test_data$sp)@coords
palette(viridis::plasma(15))
plotLeaflet(osu_truth$vars[["sumo_net"]]$config$bbox) %>%
      addCircles(lng = exemplars[, 1], lat = exemplars[, 2], 
                 col = palette()[match(test_data$cluster, unique(test_data$cluster)) %% length(palette()) + 1L],
                 radius=1.75, stroke = FALSE, fillOpacity = 0.65)

results_osu <- runValidation(test_data)

## View most stable solution data 
palette(viridis::plasma(15))
rsl_results <- results_osu$data[["rsl"]][[results_osu$most_stable]]$cluster
non_noise <- rsl_results != 0
plotLeaflet(osu_truth$vars[["sumo_net"]]$config$bbox) %>%
      addCircles(lng = exemplars[non_noise, 1], lat = exemplars[non_noise, 2], 
                 col = palette()[match(rsl_results[non_noise], unique(rsl_results[non_noise])) %% length(palette()) + 1L],
                 radius=1.75, stroke = FALSE, fillOpacity = 0.65)


## Results plotting
suppressMessages({ library("ggplot2", quietly = T) })
ari_plot <- ggplot2::ggplot()
ari_plot + ggplot2::ggtitle(paste0("OSU", " Validation: ARI")) +
  ggplot2::geom_boxplot(data = results_osu$results[CVI == "ARI"], aes(x = .id, y = score), 
                        color = sample(viridis::viridis(length(levels(results_osu$results$.id))))) +
  ggplot2::theme(axis.text.x = element_text(angle = 60, hjust = 1),
                 axis.title.x = element_blank()) +
  ggplot2::labs(y = "Adjusted Rand Index") + ggplot2::ylim(c(0, 1)) + 
  ggplot2::geom_hline(yintercept = results_osu$results[.id == "RSL" & CVI == "ARI" & index == results_osu$most_stable]$score, col = "orange")

## Save 
osu_all <- list(truth=osu_truth, validation=results_osu)
save(osu_all, file = "~/WaCS/SIGSPATIAL17/osu_all.rdata")
```





