// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_traci
void test_traci();
RcppExport SEXP sumor_test_traci() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_traci();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"sumor_test_traci", (DL_FUNC) &sumor_test_traci, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_sumor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
