# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_traci <- function() {
    invisible(.Call('sumor_test_traci', PACKAGE = 'sumor'))
}

