# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCO2 <- function(start, duration) {
    .Call('_sumor_getCO2', PACKAGE = 'sumor', start, duration)
}

getJunctions_int <- function() {
    .Call('_sumor_getJunctions_int', PACKAGE = 'sumor')
}

getPedestrianPositions <- function(start, duration) {
    .Call('_sumor_getPedestrianPositions', PACKAGE = 'sumor', start, duration)
}

getVehiclePositions <- function(start, duration) {
    .Call('_sumor_getVehiclePositions', PACKAGE = 'sumor', start, duration)
}

getVehicleFuelConsumption <- function(start, duration) {
    .Call('_sumor_getVehicleFuelConsumption', PACKAGE = 'sumor', start, duration)
}

